const DRAWING_WIDTH = 100
const DRAWING_HEIGHT = 67
const BOARD_UPPER_LEFT_X = 20.7
const BOARD_UPPER_LEFT_Y = 3
const BOARD_SQUARE_WIDTH = 8.6
const BOARD_SQUARE_HEIGHT = 6.82
const PIECE_SIZE = 6.5
const POTENTIAL_MOVE_LENGTH = 2

const PLAYERS = {
  YELLOW: 0,
  RED: 1
}

const PLAYER_COLORS = {
  RED: '#A83232',
  YELLOW: '#E6B800'
}

const SQUARE_COLORS = {
  REGULAR: '#556B2F',
  WATER: '#4682B4',
  TRAP: '#CD853F',
  DEN: '#6B4423'
}

const PIECES = {
  RAT: 1,
  CAT: 2,
  DOG: 3,
  WOLF: 4,
  LEOPARD: 5,
  TIGER: 6,
  LION: 7,
  ELEPHANT: 8
}

const WATER_SQUARES = {
  COLUMNS: [1, 2, 4, 5],
  ROWS: [3, 4, 5]
}

const MOVEMENT = {
  NORMAL_MOVE: 1,
  HORIZONTAL_JUMP: 3,
  VERTICAL_JUMP: 4
}

window.PLAYER_COLORS = PLAYER_COLORS
window.PLAYERS = PLAYERS
window.PIECES = PIECES
window.WATER_SQUARES = WATER_SQUARES
window.MOVEMENT = MOVEMENT
window.SQUARE_COLORS = SQUARE_COLORS